language: python
python:
    - "2.6"
    - "2.7"
install: 
    - sudo pip2 install .

script:
    - make -C tests/Unit_Tests
    - make -C tests/Unit_Tests tests
    - make -C tests/Acceptance_Tests
    - make -C tests/Acceptance_Tests tests
