language: python
python:
    # Python 2
    # - "2.6" (TODO: Fix 2.6 compilation)
    - "2.7"
    # Python 3
    - "3.2"
    - "3.3"
    - "3.4"
    - "3.5"
install: 
    - pip install .

script:
    - make -C tests/Unit_Tests
    - make -C tests/Unit_Tests tests
    - make -C tests/Acceptance_Tests
    - make -C tests/Acceptance_Tests tests
